server:
  port: 9090


spring:
  data:
    mongodb:
      uri: mongodb+srv://abhisek_db_user:wDaAcNfg33KB505k@cluster0.nl5haet.mongodb.net/journaldb


logging:
  level:
    personal:
      abhisek: OFF


weather:
  api:
    key: 92e15afaa0ce449394245724251711