server:
  port: 9090


spring:
  data:
    redis:
      url: redis://default:rOHoprT2BZF2ztYafnVJKicpLNi1HbUf@redis-12486.crce206.ap-south-1-1.ec2.cloud.redislabs.com:12486
    mongodb:
      uri: mongodb+srv://abhisek_db_user:wDaAcNfg33KB505k@cluster0.nl5haet.mongodb.net/journaldb

  mail:
    host: smtp.gmail.com
    port: 587
    username: nayaksuman115@gmail.com
    password: npbw lfvx rzpx ajyx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    personal:
      abhisek: OFF


weather:
  api:
    key: 92e15afaa0ce449394245724251711